// Package tor generates the torrc for an OnionForge instance.
package tor

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Service is one onion service in the generated torrc.
type Service struct {
	Name string
	Dir  string
}

// Options for torrc generation.
type Options struct {
	// DataDirectory is Tor's own state (guards, consensus cache). It lives
	// inside the persistent volume so guard selection survives restarts.
	DataDirectory string
	// Listener is the local address every onion service forwards to (Caddy).
	Listener string
	// ConfigSource is mentioned in the header comment.
	ConfigSource string
}

// Generate renders a torrc. All values must already be validated: service
// names and directories are restricted to safe characters by the config
// package.
func Generate(opts Options, services []Service) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by OnionForge from %s.\n", opts.ConfigSource)
	b.WriteString("# Do not edit: this file is rewritten on every start and reload.\n\n")
	fmt.Fprintf(&b, "DataDirectory %s\n", filepath.Clean(opts.DataDirectory))
	b.WriteString("Log notice stdout\n")
	b.WriteString("# OnionForge only publishes onion services: no SOCKS proxy, no relay.\n")
	b.WriteString("SocksPort 0\n")
	b.WriteString("ClientOnly 1\n")
	b.WriteString("RunAsDaemon 0\n")
	for _, s := range services {
		fmt.Fprintf(&b, "\n# %s\n", s.Name)
		fmt.Fprintf(&b, "HiddenServiceDir %s\n", filepath.Clean(s.Dir))
		b.WriteString("HiddenServiceVersion 3\n")
		fmt.Fprintf(&b, "HiddenServicePort 80 %s\n", opts.Listener)
	}
	return b.String()
}
