// Package caddy generates the Caddyfile that routes each onion hostname to
// its upstream, and talks to Caddy's admin API for reloads and health checks.
package caddy

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/emon5122/onionforge/internal/config"
)

// Route is one onion hostname → upstream mapping.
type Route struct {
	Hostname string // authoritative hostname read from Tor's hostname file
	Service  *config.Service
}

// Options for Caddyfile generation.
type Options struct {
	// ListenHost and ListenPort form the local listener Tor forwards to.
	ListenHost string
	ListenPort int
	// AdminSocket is the unix socket for Caddy's admin API.
	AdminSocket string
	// AccessLog enables per-request logging.
	AccessLog bool
	// ConfigSource is mentioned in the header comment.
	ConfigSource string
}

// Generate renders the Caddyfile. The configuration contains only onion
// hostnames, upstream addresses and TLS settings, never key material.
//
// Every upstream comes from static configuration: there is no placeholder or
// request-derived value anywhere in an upstream address, so a client cannot
// steer the proxy to another destination (no open proxy).
func Generate(opts Options, routes []Route) string {
	var b strings.Builder
	w := func(indent int, format string, args ...any) {
		b.WriteString(strings.Repeat("\t", indent))
		fmt.Fprintf(&b, format, args...)
		b.WriteString("\n")
	}

	w(0, "# Generated by OnionForge from %s.", opts.ConfigSource)
	w(0, "# Do not edit: this file is rewritten on every start and reload.")
	w(0, "{")
	w(1, "admin unix/%s", opts.AdminSocket)
	w(1, "persist_config off")
	w(1, "auto_https off")
	w(1, "http_port %d", opts.ListenPort)
	w(1, "default_bind %s", opts.ListenHost)
	w(1, "grace_period 5s")
	w(1, "log {")
	w(2, "output stdout")
	w(2, "format console {")
	w(3, "level_format upper")
	w(3, "time_format wall_milli")
	w(2, "}")
	w(2, "level INFO")
	// Health checks poll the admin API every few seconds; keep them quiet.
	w(2, "exclude admin.api")
	w(1, "}")
	w(1, "servers {")
	// Tor delivers plain HTTP/1.1; HTTP/2 and HTTP/3 need TLS.
	w(2, "protocols h1")
	w(1, "}")
	w(0, "}")

	for _, r := range routes {
		svc := r.Service
		t := svc.Upstream
		b.WriteString("\n")
		w(0, "# service: %s", svc.Name)
		w(0, "http://%s {", r.Hostname)
		if opts.AccessLog {
			w(1, "log")
		}
		if t.BasePath != "" {
			// /x on the onion side becomes <base>/x upstream. {uri} keeps the
			// original escaping and query string.
			w(1, "rewrite * %s{uri}", t.BasePath)
		}
		w(1, "reverse_proxy %s {", t.URL())
		switch hh := svc.EffectiveHostHeader(); hh {
		case config.HostPreserve:
			// Caddy forwards the incoming (.onion) Host header by default.
		case config.HostUpstream:
			w(2, "header_up Host {upstream_hostport}")
		default:
			w(2, "header_up Host %s", hh)
		}
		if svc.RewriteRedirects {
			w(2, "header_down Location `%s` `http://{http.request.host}%s`", redirectPattern(svc), redirectReplacement(svc))
		}
		if t.Scheme == "https" {
			tls := svc.TLS
			if tls.InsecureSkipVerify || tls.ServerName != "" || tls.CAFile != "" {
				w(2, "transport http {")
				if tls.ServerName != "" {
					w(3, "tls_server_name %s", tls.ServerName)
				}
				if tls.CAFile != "" {
					w(3, "tls_trust_pool file %s", tls.CAFile)
				}
				if tls.InsecureSkipVerify {
					w(3, "tls_insecure_skip_verify")
				}
				w(2, "}")
			}
		}
		w(1, "}")
		w(0, "}")
	}

	// Anything else (unknown Host header, direct access to the listener) is
	// refused rather than routed anywhere.
	b.WriteString("\n")
	w(0, "# Requests for unknown hostnames are rejected.")
	w(0, "http:// {")
	w(1, "respond \"Unknown onion service\" 421 {")
	w(2, "close")
	w(1, "}")
	w(0, "}")
	return b.String()
}

// redirectPattern matches absolute Location headers pointing at the target's
// own origin (any scheme/port on the same host), including the base path.
func redirectPattern(svc *config.Service) string {
	t := svc.Upstream
	host := regexp.QuoteMeta(t.Host)
	if strings.Contains(t.Host, ":") {
		host = `\[` + host + `\]`
	}
	p := `(?i)^https?://` + host + `(?::\d+)?`
	if t.BasePath != "" {
		return p + regexp.QuoteMeta(t.BasePath) + `(/|$)`
	}
	return p
}

func redirectReplacement(svc *config.Service) string {
	if svc.Upstream.BasePath != "" {
		return "/"
	}
	return ""
}
